Fe setup
cplprince/kingdoms pull request #1
Opened 2023-09-22 10:58 UTC by Patrik93JS

Tak jdem na to :D

2023-09-23 11:13 UTC, cplprince requested changes

2023-09-23 11:13 UTC, cplprince commented on FE/package.json
> +    "typescript": "5.2.2"
dev: typescript, taiwind, postcss, eslint, autoprefixer, @types

prosím přehodit

2023-09-23 11:13 UTC, cplprince commented on FE/src/app/layout.tsx
> +      <Providers>
když už máš providers komponentu, tak tam dej všechny providery :)

2023-09-23 11:13 UTC, cplprince commented on FE/src/app/layout.tsx
> +import { Providers } from "@/store/provider";
soubor by se měl jmenovat stejně jako funkce uvnitř

2023-09-23 11:13 UTC, cplprince commented on FE/src/app/layout.tsx
> +"use client";
byl bych raději kdyby jsi "use client" neměl na layoutu

2023-09-23 11:13 UTC, cplprince commented on FE/src/app/page.tsx
> +    <main className="flex min-h-screen flex-col items-center justify-between p-24">
rozjeď si kdyžtak zase clsx na classy :)

2023-09-23 11:13 UTC, cplprince commented on FE/src/store/hooks.ts
proč máš tady tne hooks.ts a zároveň máš ty stejné hooky ve store.ts???

2023-09-23 11:13 UTC, cplprince commented on FE/tailwind.config.ts
> +    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
pages nemame, smazat

2023-09-24 04:36 UTC, Patrik93JS commented on FE/tailwind.config.ts
> +    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
Já ten config hnedka upravím aji na tu naši paletu jak jsme se včera bavili, ok?

2023-09-24 10:40 UTC, cplprince approved these changes

2023-09-24 11:02 UTC, merged